"use client";

import { useState } from "react";
import { Octokit } from "@octokit/rest";
import { GitGraph, Loader2, CheckCircle2, AlertCircle } from "lucide-react";

interface GitHubExportProps {
  code: string;
}

export function GitHubExport({ code }: GitHubExportProps) {
  const [token, setToken] = useState("");
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState<"idle" | "success" | "error">("idle");
  const [message, setMessage] = useState("");
  const [url, setUrl] = useState("");

  const handleExport = async (type: "gist" | "repo") => {
    if (!token) {
      setStatus("error");
      setMessage("Please enter a GitHub Personal Access Token.");
      return;
    }
    
    if (!code) {
      setStatus("error");
      setMessage("No code to export.");
      return;
    }

    setLoading(true);
    setStatus("idle");
    
    try {
      const octokit = new Octokit({ auth: token });
      
      if (type === "gist") {
        const response = await octokit.rest.gists.create({
          description: "Generated by AI App Builder",
          public: false,
          files: {
            "App.tsx": {
              content: code,
            },
          },
        });
        setUrl(response.data.html_url || "");
      } else {
        // Create standard repo with the single Next.js/React file (simplified logic)
        // Usually, initializing a full repo takes multiple files. For MVP, we'll just create a repo 
        // with App.tsx.
        const user = await octokit.rest.users.getAuthenticated();
        const repoName = `ai-generated-app-${Date.now()}`;
        
        const repoResponse = await octokit.rest.repos.createForAuthenticatedUser({
          name: repoName,
          description: "Scaffolded via AI App Builder",
          private: true,
          auto_init: true,
        });

        await octokit.rest.repos.createOrUpdateFileContents({
          owner: user.data.login,
          repo: repoName,
          path: "src/App.tsx",
          message: "Initial commit by AI",
          content: btoa(code), // Base64 encoding for API
        });
        
        setUrl(repoResponse.data.html_url || "");
      }
      
      setStatus("success");
      setMessage(`Successfully exported to ${type.toUpperCase()}!`);
    } catch (error: unknown) {
      setStatus("error");
      setMessage((error as Error).message || "Failed to export");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="w-full bg-white border border-zinc-200 rounded-xl p-4 shadow-sm hover:shadow-md transition-all">
      <div className="flex items-center space-x-2 mb-4">
        <GitGraph className="text-zinc-600" size={20} />
        <h3 className="font-semibold text-zinc-800">Export to GitHub</h3>
      </div>
      
      <div className="space-y-3">
        <input
          type="password"
          placeholder="GitHub Personal Access Token"
          value={token}
          onChange={(e) => setToken(e.target.value)}
          className="w-full bg-zinc-50 border border-zinc-300 rounded-lg p-2.5 text-sm text-zinc-900 focus:outline-none focus:ring-1 focus:ring-zinc-500"
        />
        
        <div className="flex space-x-3">
          <button
            onClick={() => handleExport("gist")}
            disabled={loading || !token || !code}
            className="flex-1 bg-zinc-100 hover:bg-zinc-200 border border-zinc-300 text-zinc-800 py-2 px-4 rounded-lg text-sm font-medium transition-colors disabled:opacity-50 flex justify-center items-center"
          >
            {loading ? <Loader2 size={16} className="animate-spin" /> : "Create Gist"}
          </button>
          <button
            onClick={() => handleExport("repo")}
            disabled={loading || !token || !code}
            className="flex-1 bg-zinc-900 hover:bg-zinc-800 text-white py-2 px-4 rounded-lg text-sm font-medium transition-colors disabled:opacity-50 flex justify-center items-center"
          >
            {loading ? <Loader2 size={16} className="animate-spin" /> : "Create Repo"}
          </button>
        </div>

        {status !== "idle" && (
          <div className={`p-3 rounded-lg flex items-start space-x-2 text-sm ${status === "success" ? "bg-emerald-900/30 text-emerald-400" : "bg-red-900/30 text-red-400"}`}>
            {status === "success" ? <CheckCircle2 size={16} className="mt-0.5 shrink-0" /> : <AlertCircle size={16} className="mt-0.5 shrink-0" />}
            <div className="flex flex-col">
              <span>{message}</span>
              {url && (
                <a href={url} target="_blank" rel="noreferrer" className="underline font-medium hover:text-emerald-300 transition-colors mt-1">
                  View on GitHub
                </a>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
